-- ── USUARIOS ────────────────────────────────────────────────
INSERT INTO usuarios (usr_nombre, usr_apellido, usr_correo, usr_tipo_usuario, usr_contrasena, usr_telefono) VALUES
                                                                                                                ('Admin',   'PetSit',   'admin@petsit.com',  'ADMINISTRADOR', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lh3y', '1100000001'),
                                                                                                                ('Agustin', 'Segovia',  'agus@gmail.com',    'DUENO',         '$2a$10$TbOBMm7cEFJi0DRnpMq5GOGJbu9PB6B9U0M3kUCJxgU6FoWWVRiAO', '1122334455'),
                                                                                                                ('Maia',    'Cohen',    'maia@gmail.com',    'DUENO',         '$2a$10$6trNoPiP5N9OY9VjuMKjDO8H7xm6VQBM7uKH1jMlOCXZBw0UDHMya', '1122334456'),
                                                                                                                ('Carlos',  'Ferreira', 'carlos@gmail.com',  'DUENO',         '$2a$10$8KIryFNmGkLHq0J6Z6VUa.Tnd7xMfJ4kQhOGYk0G0fHQ1dRcGfRyy', '1122334457');

-- ── VETERINARIAS ────────────────────────────────────────────
INSERT INTO veterinarias (vet_nombre, vet_direccion, vet_telefono, vet_horario_atencion, vet_ubicacion, vet_activa, vet_lat, vet_lng, vet_estado_aprobacion) VALUES
                                                                                                                                                                 ('Clinica Veterinaria Belgrano', 'Moldes 2345, Belgrano',         '+54 11 4555-1111', 'Lun a Dom 24hs',         'Belgrano, CABA',      TRUE,  -34.5621, -58.4581, 'APROBADA'),
                                                                                                                                                                 ('Patitas Caballito',            'Hidalgo 987, Caballito',         '+54 11 4321-3333', 'Lun a Sab 9-20hs',      'Caballito, CABA',     TRUE,  -34.6189, -58.4444, 'APROBADA'),
                                                                                                                                                                 ('Love Pets Palermo',            'Av. Santa Fe 123, Palermo',      '+54 11 4000-7777', 'Lun a Dom 8-22hs',      'Palermo, CABA',       TRUE,  -34.5875, -58.4103, 'APROBADA'),
                                                                                                                                                                 ('BlackDog Almagro',             'Corrientes 3560, Almagro',       '+54 11 4777-1212', 'Lun a Sab 9-21hs',      'Almagro, CABA',       TRUE,  -34.6061, -58.4203, 'APROBADA'),
                                                                                                                                                                 ('Galia Vet Recoleta',           'Azcuenaga 1450, Recoleta',       '+54 11 4511-9090', 'Lun a Dom 24hs',         'Recoleta, CABA',      TRUE,  -34.5879, -58.3930, 'APROBADA'),
                                                                                                                                                                 ('Hub City Palermo',             'Honduras 4901, Palermo',         '+54 11 4899-2200', 'Lun a Vie 10-20hs',     'Palermo, CABA',       TRUE,  -34.5853, -58.4274, 'APROBADA'),
                                                                                                                                                                 ('Pet World Saavedra',           'Balbin 4700, Saavedra',          '+54 11 4701-3344', 'Lun a Dom 8-23hs',      'Saavedra, CABA',      TRUE,  -34.5539, -58.4894, 'APROBADA'),
                                                                                                                                                                 ('Master-Animal Villa Urquiza',  'Av. Monroe 5200, Villa Urquiza', '+54 11 4521-7788', 'Lun a Sab 9-20hs',      'Villa Urquiza, CABA', TRUE,  -34.5733, -58.4867, 'APROBADA'),
                                                                                                                                                                 ('PetCare Lanus',                'Calle Mitre 432, Lanus',         '1133445566',       'Todos los dias 8-20hs', 'Lanus, GBA',          TRUE,  -34.7083, -58.3906, 'APROBADA'),
                                                                                                                                                                 ('Salud Animal Quilmes',         'Diagonal Norte 100, Quilmes',    '1144556677',       'Lun a Sab 10-17hs',     'Quilmes, GBA',        FALSE, -34.7206, -58.2538, 'APROBADA');

-- ── REFUGIOS ────────────────────────────────────────────────
INSERT INTO refugios (ref_nombre, ref_direccion, ref_telefono, ref_correo, ref_foto, ref_ubicacion, ref_lat, ref_lng, ref_activa, ref_estado_aprobacion) VALUES
                                                                                                                                                             ('Lost & Found',          'Av. Francisco Beiro 4567, Villa Devoto', '+54 11 4567-8901', 'info@lostandfound.org.ar',  'arca-peludos.png',  'Villa Devoto, CABA',  -34.5969, -58.5133, TRUE, 'APROBADA'),
                                                                                                                                                             ('Animal Resource Center','Neuquen 1234, Caballito',                '+54 11 4321-2222', 'contacto@arc.org.ar',        'cielo-mascotas.png','Caballito, CABA',     -34.6189, -58.4444, TRUE, 'APROBADA'),
                                                                                                                                                             ('America Dog & Cat Hotel','Zapiola 2230, Colegiales',              '+54 11 4782-3010', 'hola@americapets.com.ar',    'america.jpg',       'Colegiales, CABA',    -34.5753, -58.4474, TRUE, 'APROBADA'),
                                                                                                                                                             ('Animal Care Belgrano',  'Juramento 2450, Belgrano',               '+54 11 4786-1122', 'atencion@animalcare.com.ar', 'animal-care.jpg',   'Belgrano, CABA',      -34.5622, -58.4587, TRUE, 'APROBADA'),
                                                                                                                                                             ('Friends Recoleta',      'Av. Callao 980, Recoleta',               '+54 11 4371-8899', 'friends@refugio.org.ar',     'friends.jpg',       'Recoleta, CABA',      -34.5879, -58.3930, TRUE, 'APROBADA'),
                                                                                                                                                             ('Greenville Caballito',  'Av. Pedro Goyena 850, Caballito',        '+54 11 4901-3377', 'info@greenville.org.ar',     'Greenville.jpg',    'Caballito, CABA',     -34.6225, -58.4469, TRUE, 'APROBADA'),
                                                                                                                                                             ('Petland Palermo',       'Av. Santa Fe 4100, Palermo',             '+54 11 4832-7700', 'contacto@petland.com.ar',    'petland.jpg',       'Palermo, CABA',       -34.5853, -58.4274, TRUE, 'APROBADA'),
                                                                                                                                                             ('The Pets Hotel',        'Av. Monroe 5200, Villa Urquiza',         '+54 11 4543-2290', 'hotel@thepetshotel.com.ar',  'pets-hotel.jpg',    'Villa Urquiza, CABA', -34.5733, -58.4867, TRUE, 'APROBADA'),
                                                                                                                                                             ('Vida Animal Belgrano',  'Virrey del Pino 2750, Belgrano',         '+54 11 4781-5566', 'vidaanimal@refugio.org.ar',  'vida-animal.jpg',   'Belgrano, CABA',      -34.5580, -58.4542, TRUE, 'APROBADA'),
                                                                                                                                                             ('Refugio Esperanza',     'Av. Rivadavia 5000, Caballito',          '1122334455',       'esperanza@refugio.org',      'esperanza.jpg',     'Buenos Aires',        -34.6189, -58.4500, TRUE, 'APROBADA');

-- ── MASCOTAS ────────────────────────────────────────────────
INSERT INTO mascotas (msc_nombre, msc_raza, msc_color, msc_tamano, msc_edad, msc_descripcion, msc_foto, msc_sexo, msc_dueno_id) VALUES
                                                                                                                                    ('Firulais', 'Labrador', 'Negro',  'grande',  5, 'Muy jugeton y sociable',       'firulais.jpg', 'Macho',  2),
                                                                                                                                    ('Mimi',     'Caniche',  'Blanco', 'chico',   3, 'Le teme a los ruidos fuertes', 'mimi.jpg',     'Hembra', 2),
                                                                                                                                    ('Toby',     'Mestizo',  'Marron', 'mediano', 4, 'Rescatado de la calle',        'toby.jpg',     'Macho',  3),
                                                                                                                                    ('Luna',     'Siames',   'Gris',   'chico',   2, 'Tranquila y carinosa',         'luna.jpg',     'Hembra', 3);

-- ── ADOPCIONES ──────────────────────────────────────────────
INSERT INTO adopciones (ado_mascota_id, ado_usuario_id, ado_estado, ado_descripcion) VALUES
                                                                                         (3, 3, 'ACTIVA', 'Toby busca una familia responsable con espacio para paseos'),
                                                                                         (2, 2, 'ACTIVA', 'Mimi necesita un hogar tranquilo sin ninos pequenos'),
                                                                                         (4, 3, 'ACTIVA', 'Luna es ideal para departamento, muy independiente');

-- ── ALERTAS ─────────────────────────────────────────────────
INSERT INTO alertas (alt_usuario_id, alt_descripcion, alt_lat, alt_lng) VALUES
                                                                            (2, 'Visto en Plaza Italia',    -34.5873, -58.4100),
                                                                            (2, 'Se perdio en Microcentro', -34.6037, -58.3816);

-- ── REPORTES DEMO ───────────────────────────────────────────
INSERT INTO reportes (rep_usuario_id, rep_tipo_reporte, rep_estado_mascota, rep_descripcion, rep_ubicacion, rep_estado, rep_lat, rep_lng) VALUES
                                                                                                                                              (2, 'MASCOTA_PERDIDA', 'PERDIDO',    'Milo - Perro mestizo, collar verde',          'Palermo',       'PENDIENTE', -34.5875, -58.4103),
                                                                                                                                              (3, 'TENGO_CONMIGO',   'ENCONTRADO', 'Nube - Gato Ragdoll, mimoso y limpio',         'Belgrano',      'PENDIENTE', -34.5622, -58.4587),
                                                                                                                                              (2, 'MASCOTA_PERDIDA', 'PERDIDO',    'Nina - Gata Scottish Fold, ojos ambar',        'Recoleta',      'PENDIENTE', -34.5879, -58.3930),
                                                                                                                                              (3, 'SOLO_LO_VI',      'ENCONTRADO', 'Perro blanco y negro sin correa',              'Boedo',         'PENDIENTE', -34.6286, -58.4173),
                                                                                                                                              (2, 'MASCOTA_PERDIDA', 'PERDIDO',    'Koko - Gato siames, ojos azules',             'Caballito',     'PENDIENTE', -34.6189, -58.4444),
                                                                                                                                              (3, 'TENGO_CONMIGO',   'ENCONTRADO', 'Lola - Shih Tzu sin correa, collar sin chapita','Almagro',      'PENDIENTE', -34.6061, -58.4203),
                                                                                                                                              (2, 'MASCOTA_PERDIDA', 'PERDIDO',    'Roma - Border Collie, collar celeste',         'Colegiales',    'PENDIENTE', -34.5753, -58.4474),
                                                                                                                                              (3, 'SOLO_LO_VI',      'ENCONTRADO', 'Toby - Beagle con collar negro',              'San Telmo',     'PENDIENTE', -34.6162, -58.3712),
                                                                                                                                              (2, 'MASCOTA_PERDIDA', 'PERDIDO',    'Sombra - Perro negro con manchita blanca',    'Saavedra',      'PENDIENTE', -34.5539, -58.4894),
                                                                                                                                              (3, 'TENGO_CONMIGO',   'ENCONTRADO', 'Bruno - Rottweiler tranquilo, sin guia',      'Flores',        'PENDIENTE', -34.6282, -58.4602),
                                                                                                                                              (2, 'MASCOTA_PERDIDA', 'PERDIDO',    'Lia - Perra Podenco, orejas grandes',         'Nunez',         'PENDIENTE', -34.5487, -58.4564),
                                                                                                                                              (3, 'SOLO_LO_VI',      'ENCONTRADO', 'Perro mestizo corriendo sin correa',          'Villa Urquiza', 'PENDIENTE', -34.5733, -58.4867);
